import { fieldTypes } from '@/utilities/constants';
import { Box } from '@chakra-ui/react';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';
import 'ag-grid-enterprise';
import { AgGridReact } from 'ag-grid-react';

import {
  Action,
  Bdm,
  Cis,
  Coms,
  CustomerName,
  Experience,
  Gpb,
  Guidelines,
  Job,
  LifeCycle,
  Ms,
  Nnb,
  On,
  Project,
  Rocks,
  Status,
  Tier,
} from './CustomCellRenderer';
import GridTopHeader from './GridTopHeader';

// import GridTopHeader from './GridTopHeader';

export default function GridView() {
  const Coldata = [
    { headerName: 'Customer Name', field: 'customername' },
    { headerName: 'Tier', field: 'tier' /* , rowGroup: true, hide: true */ },
    { headerName: 'Experience Level', field: 'experiencelevel' },
    { headerName: 'Region', field: 'region' },
    { headerName: 'Status', field: 'status' },
    { headerName: 'Lifecycle Stage', field: 'lifecyclestage' },
    { headerName: 'Brand or Group', field: 'brandorgroup' },
    { headerName: 'CIS', field: 'cis' },
    { headerName: 'Success Pod', field: 'successpod' },
    { headerName: 'Action', field: 'action', pinned: 'right' },
    { headerName: 'Classification', field: 'classification' },
    { headerName: 'Channels', field: 'channels' },
    { headerName: 'Tradefull Marketplaces', field: 'tm' },
    { headerName: 'Fulfillment Type', field: 'ft' },
    { headerName: 'Month Closed', field: 'monthclosed' },
    { headerName: 'Contract Sign Date', field: 'csd' },
    { headerName: 'Onboarding Start Date', field: 'osd' },
    { headerName: 'Jira Onboarding Project', field: 'job' },
    { headerName: 'Onboard Live Date', field: 'old' },
    { headerName: 'Onboarding Notes', field: 'on' },
    { headerName: 'Health Score', field: 'healthscore' },
    { headerName: 'Expected Annual GMV', field: 'eag' },
    { headerName: '.coms', field: 'coms' },
    { headerName: 'Notes / Next Steps / Blockers', field: 'nnb' },
    { headerName: 'Business Development Manager', field: 'bdm' },
    { headerName: 'Customer Time Zone', field: 'time' },
    { headerName: 'CX Time Member', field: 'cx' },
    { headerName: 'Marketplace Summary', field: 'ms' },
    { headerName: 'Approved Monthly Advertising Budget', field: 'amab' },
    { headerName: 'Strategy Call Cadence', field: 'scc' },
    { headerName: 'Strategy Rocks', field: 'rocks' },
    { headerName: 'GMV Projection Basis', field: 'gpb' },
    { headerName: 'Strategic Customer', field: 'sc' },
    { headerName: 'First Sale Date', field: 'saledate' },
    { headerName: 'Full Run Rate Date', field: 'runrate' },
    { headerName: 'Experience Call Cadence', field: 'ecc' },
    { headerName: 'Using our Advertising', field: 'using' },
    { headerName: 'Platform', field: 'platform' },
    { headerName: 'Customers Seasonality', field: 'season' },
    { headerName: 'RMA Handling Options', field: 'rma' },
    { headerName: 'Customer Return Guidelines', field: 'guidelines' },
    { headerName: 'date of eComm call', field: 'ecomm' },
    { headerName: 'Project Manager', field: 'project' },
    { headerName: 'Flagged Customer', field: 'flagged' },
  ];
  const rowData = [
    {
      customername: 'Compass Health',
      tier: 'Bronze',
      experiencelevel: 'Standard',
      region: 'North America',
      status: 'Inactive',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Initiate Onboarding',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'A Helm',
      tier: 'Gold',
      experiencelevel: 'Premier',
      region: 'North America',
      status: 'Active',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Show Details',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'Ambani Home',
      tier: 'Platinum',
      experiencelevel: 'Signature',
      region: 'North America',
      status: 'Active',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Initiate Onboarding',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'Asobu',
      tier: 'Silver',
      experiencelevel: 'Premier',
      region: 'APAC',
      status: 'Active',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Show Details',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'ABC Packaging',
      tier: 'Gold',
      experiencelevel: 'Signature',
      region: 'APAC',
      status: 'Inactive',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Show Details',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'Bob Johnson',
      tier: 'Platinum',
      experiencelevel: 'Standard',
      region: 'APAC',
      status: 'Active',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Initiate Onboarding',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'Arthur',
      tier: 'Bronze',
      experiencelevel: 'Standard',
      region: 'North America',
      status: 'Inactive',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Show Details',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'USA LLC',
      tier: 'Bronze',
      experiencelevel: 'Premier',
      region: 'APAC',
      status: 'Inactive',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Initiate Onboarding',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'Compass Health',
      tier: 'Bronze',
      experiencelevel: 'Standard',
      region: 'North America',
      status: 'Inactive',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Initiate Onboarding',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'A Helm',
      tier: 'Gold',
      experiencelevel: 'Premier',
      region: 'North America',
      status: 'Active',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Show Details',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'Ambani Home',
      tier: 'Platinum',
      experiencelevel: 'Signature',
      region: 'North America',
      status: 'Active',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Initiate Onboarding',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'Asobu',
      tier: 'Silver',
      experiencelevel: 'Premier',
      region: 'APAC',
      status: 'Active',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Show Details',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'ABC Packaging',
      tier: 'Gold',
      experiencelevel: 'Signature',
      region: 'APAC',
      status: 'Inactive',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Show Details',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'Bob Johnson',
      tier: 'Platinum',
      experiencelevel: 'Standard',
      region: 'APAC',
      status: 'Active',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Initiate Onboarding',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'Arthur',
      tier: 'Bronze',
      experiencelevel: 'Standard',
      region: 'North America',
      status: 'Inactive',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Show Details',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
    {
      customername: 'USA LLC',
      tier: 'Bronze',
      experiencelevel: 'Premier',
      region: 'APAC',
      status: 'Inactive',
      lifecyclestage: 'Identity',
      brandorgroup: 'REV Referral',
      cis: 'John',
      successpod: 'Elevate X',
      action: 'Initiate Onboarding',
      classification: 'Reseller',
      channels: 'B2B',
      tm: 'Ebay',
      ft: '3PL',
      monthclosed: 'May',
      csd: '6/22/23',
      osd: '6/22/23',
      job: 'View Link',
      old: '6/22/23',
      on: 'View Entries',
      healthscore: '',
      eag: '$300,000.00',
      coms: 'View Link',
      nnb: 'View Entries',
      bdm: 'Tom',
      time: '',
      cx: '',
      ms: 'View Entries',
      amab: '$300,00.00',
      scc: 'Bi-Weekly',
      rocks: 'View Entries',
      gpb: 'View Entries',
      sc: 'TRUE',
      saledate: '6/22/23',
      runrate: '6/22/23',
      ecc: 'Bi-Weekly',
      using: 'no',
      platform: 'Shopify',
      season: 'N/A',
      rma: 'Standard Liquidation',
      guidelines: 'View Details',
      ecomm: '6/22/23',
      project: 'Jack',
      flagged: 'FALSE',
    },
  ];

  const cellRendererSelector = (params: any) => {
    switch (params?.colDef?.field) {
      case fieldTypes?.CUSTOMERNAME:
        return {
          component: CustomerName,
        };
      case fieldTypes?.TIER:
        return {
          component: Tier,
        };
      case fieldTypes?.EXPERIENCELEVEL:
        return {
          component: Experience,
        };
      case fieldTypes?.STATUS:
        return {
          component: Status,
        };
      case fieldTypes?.LIFECYCLE:
        return {
          component: LifeCycle,
        };
      case fieldTypes?.ACTION:
        return {
          component: Action,
        };

      case fieldTypes?.CIS:
        return {
          component: Cis,
        };
      case fieldTypes?.BDM:
        return {
          component: Bdm,
        };
      case fieldTypes?.PROJECT:
        return {
          component: Project,
        };
      case fieldTypes?.GUIDELINES:
        return {
          component: Guidelines,
        };
      case fieldTypes?.GPB:
        return {
          component: Gpb,
        };
      case fieldTypes?.ROCKS:
        return {
          component: Rocks,
        };
      case fieldTypes?.MS:
        return {
          component: Ms,
        };
      case fieldTypes?.NNB:
        return {
          component: Nnb,
        };
      case fieldTypes?.ON:
        return {
          component: On,
        };
      case fieldTypes?.JOB:
        return {
          component: Job,
        };
      case fieldTypes?.COMS:
        return {
          component: Coms,
        };

      default:
        return undefined;
    }
  };

  const columnDefs: any = Coldata.map((item) => {
    return {
      field: item?.field,
      headerName: item?.headerName,
      pinned: item?.pinned,
      cellRendererSelector,
      // rowGroup: item?.rowGroup,
      // hide: item?.hide,
      resizeable: true,
      sortable: true,
      filter: true,
    };
  });

  const gridOptions: any = {
    rowHeight: 47,
    // autoGroupColumnDef: {
    //   headerName: 'Tier',
    //   field: 'tier',
    // },
  };

  return (
    <Box
      // className="main-grid mb-3"
      mt={0}
      mb={3}
      ms={5}
      me={5}
      border="1px"
      borderColor="gray.200"
      borderRadius="base"
    >
      <GridTopHeader />
      <Box className="ag-theme-alpine" style={{ height: 480, width: 'auto' }}>
        <AgGridReact
          rowData={rowData}
          columnDefs={columnDefs}
          gridOptions={gridOptions}
          animateRows
        />
      </Box>
    </Box>
  );
}
